// Generated by `dart run bin/file-icons/emit_typescript_icons.dart` from tools/assets/languages.json — do not edit.

import {
  BracketsCurlyIcon,
  CoffeeIcon,
  FileIcon,
  FileSqlIcon,
  GifIcon,
  ImageIcon,
  TerminalIcon,
} from '@phosphor-icons/react';

import adaGlyph from '../assets/file-icons/ada.svg?no-inline';
import androidGlyph from '../assets/file-icons/android.svg?no-inline';
import apacheGlyph from '../assets/file-icons/apache.svg?no-inline';
import apachegroovyGlyph from '../assets/file-icons/apachegroovy.svg?no-inline';
import apachemavenGlyph from '../assets/file-icons/apachemaven.svg?no-inline';
import appleGlyph from '../assets/file-icons/apple.svg?no-inline';
import asciidoctorGlyph from '../assets/file-icons/asciidoctor.svg?no-inline';
import astroGlyph from '../assets/file-icons/astro.svg?no-inline';
import autohotkeyGlyph from '../assets/file-icons/autohotkey.svg?no-inline';
import avaloniauiGlyph from '../assets/file-icons/avaloniaui.svg?no-inline';
import bazelGlyph from '../assets/file-icons/bazel.svg?no-inline';
import bunGlyph from '../assets/file-icons/bun.svg?no-inline';
import cGlyph from '../assets/file-icons/c.svg?no-inline';
import caddyGlyph from '../assets/file-icons/caddy.svg?no-inline';
import cocoapodsGlyph from '../assets/file-icons/cocoapods.svg?no-inline';
import coffeescriptGlyph from '../assets/file-icons/coffeescript.svg?no-inline';
import commonlispGlyph from '../assets/file-icons/commonlisp.svg?no-inline';
import composerGlyph from '../assets/file-icons/composer.svg?no-inline';
import cplusplusGlyph from '../assets/file-icons/cplusplus.svg?no-inline';
import crystalGlyph from '../assets/file-icons/crystal.svg?no-inline';
import cssGlyph from '../assets/file-icons/css.svg?no-inline';
import cucumberGlyph from '../assets/file-icons/cucumber.svg?no-inline';
import denoGlyph from '../assets/file-icons/deno.svg?no-inline';
import developmentcontainersGlyph from '../assets/file-icons/developmentcontainers.svg?no-inline';
import dockerGlyph from '../assets/file-icons/docker.svg?no-inline';
import dotenvGlyph from '../assets/file-icons/dotenv.svg?no-inline';
import dotnetGlyph from '../assets/file-icons/dotnet.svg?no-inline';
import editorconfigGlyph from '../assets/file-icons/editorconfig.svg?no-inline';
import ejsGlyph from '../assets/file-icons/ejs.svg?no-inline';
import elixirGlyph from '../assets/file-icons/elixir.svg?no-inline';
import erlangGlyph from '../assets/file-icons/erlang.svg?no-inline';
import eslintGlyph from '../assets/file-icons/eslint.svg?no-inline';
import fastlaneGlyph from '../assets/file-icons/fastlane.svg?no-inline';
import fishshellGlyph from '../assets/file-icons/fishshell.svg?no-inline';
import fortranGlyph from '../assets/file-icons/fortran.svg?no-inline';
import freedesktopdotorgGlyph from '../assets/file-icons/freedesktopdotorg.svg?no-inline';
import fsharpGlyph from '../assets/file-icons/fsharp.svg?no-inline';
import gitGlyph from '../assets/file-icons/git.svg?no-inline';
import githubGlyph from '../assets/file-icons/github.svg?no-inline';
import gleamGlyph from '../assets/file-icons/gleam.svg?no-inline';
import gnuemacsGlyph from '../assets/file-icons/gnuemacs.svg?no-inline';
import goGlyph from '../assets/file-icons/go.svg?no-inline';
import godotengineGlyph from '../assets/file-icons/godotengine.svg?no-inline';
import gradleGlyph from '../assets/file-icons/gradle.svg?no-inline';
import graphqlGlyph from '../assets/file-icons/graphql.svg?no-inline';
import handlebarsdotjsGlyph from '../assets/file-icons/handlebarsdotjs.svg?no-inline';
import haskellGlyph from '../assets/file-icons/haskell.svg?no-inline';
import haxeGlyph from '../assets/file-icons/haxe.svg?no-inline';
import homebrewGlyph from '../assets/file-icons/homebrew.svg?no-inline';
import html5Glyph from '../assets/file-icons/html5.svg?no-inline';
import jenkinsGlyph from '../assets/file-icons/jenkins.svg?no-inline';
import jestGlyph from '../assets/file-icons/jest.svg?no-inline';
import jinjaGlyph from '../assets/file-icons/jinja.svg?no-inline';
import justGlyph from '../assets/file-icons/just.svg?no-inline';
import laravelGlyph from '../assets/file-icons/laravel.svg?no-inline';
import latexGlyph from '../assets/file-icons/latex.svg?no-inline';
import lessGlyph from '../assets/file-icons/less.svg?no-inline';
import llvmGlyph from '../assets/file-icons/llvm.svg?no-inline';
import luaGlyph from '../assets/file-icons/lua.svg?no-inline';
import luauGlyph from '../assets/file-icons/luau.svg?no-inline';
import markdownGlyph from '../assets/file-icons/markdown.svg?no-inline';
import mdxGlyph from '../assets/file-icons/mdx.svg?no-inline';
import mermaidGlyph from '../assets/file-icons/mermaid.svg?no-inline';
import nginxGlyph from '../assets/file-icons/nginx.svg?no-inline';
import nimGlyph from '../assets/file-icons/nim.svg?no-inline';
import npmGlyph from '../assets/file-icons/npm.svg?no-inline';
import nushellGlyph from '../assets/file-icons/nushell.svg?no-inline';
import nvidiaGlyph from '../assets/file-icons/nvidia.svg?no-inline';
import ocamlGlyph from '../assets/file-icons/ocaml.svg?no-inline';
import odinGlyph from '../assets/file-icons/odin.svg?no-inline';
import openglGlyph from '../assets/file-icons/opengl.svg?no-inline';
import openscadGlyph from '../assets/file-icons/openscad.svg?no-inline';
import opentofuGlyph from '../assets/file-icons/opentofu.svg?no-inline';
import orgGlyph from '../assets/file-icons/org.svg?no-inline';
import pdmGlyph from '../assets/file-icons/pdm.svg?no-inline';
import perlGlyph from '../assets/file-icons/perl.svg?no-inline';
import phoenixframeworkGlyph from '../assets/file-icons/phoenixframework.svg?no-inline';
import phpGlyph from '../assets/file-icons/php.svg?no-inline';
import podmanGlyph from '../assets/file-icons/podman.svg?no-inline';
import poetryGlyph from '../assets/file-icons/poetry.svg?no-inline';
import prismaGlyph from '../assets/file-icons/prisma.svg?no-inline';
import pugGlyph from '../assets/file-icons/pug.svg?no-inline';
import purescriptGlyph from '../assets/file-icons/purescript.svg?no-inline';
import pypiGlyph from '../assets/file-icons/pypi.svg?no-inline';
import qtGlyph from '../assets/file-icons/qt.svg?no-inline';
import quartoGlyph from '../assets/file-icons/quarto.svg?no-inline';
import reactGlyph from '../assets/file-icons/react.svg?no-inline';
import robotframeworkGlyph from '../assets/file-icons/robotframework.svg?no-inline';
import rubyGlyph from '../assets/file-icons/ruby.svg?no-inline';
import rubygemsGlyph from '../assets/file-icons/rubygems.svg?no-inline';
import rustGlyph from '../assets/file-icons/rust.svg?no-inline';
import sapGlyph from '../assets/file-icons/sap.svg?no-inline';
import sassGlyph from '../assets/file-icons/sass.svg?no-inline';
import scalaGlyph from '../assets/file-icons/scala.svg?no-inline';
import shopifyGlyph from '../assets/file-icons/shopify.svg?no-inline';
import solidityGlyph from '../assets/file-icons/solidity.svg?no-inline';
import stylelintGlyph from '../assets/file-icons/stylelint.svg?no-inline';
import stylusGlyph from '../assets/file-icons/stylus.svg?no-inline';
import svelteGlyph from '../assets/file-icons/svelte.svg?no-inline';
import swiftGlyph from '../assets/file-icons/swift.svg?no-inline';
import symfonyGlyph from '../assets/file-icons/symfony.svg?no-inline';
import terraformGlyph from '../assets/file-icons/terraform.svg?no-inline';
import tmuxGlyph from '../assets/file-icons/tmux.svg?no-inline';
import tomlGlyph from '../assets/file-icons/toml.svg?no-inline';
import typescriptGlyph from '../assets/file-icons/typescript.svg?no-inline';
import typstGlyph from '../assets/file-icons/typst.svg?no-inline';
import unityGlyph from '../assets/file-icons/unity.svg?no-inline';
import uvGlyph from '../assets/file-icons/uv.svg?no-inline';
import vagrantGlyph from '../assets/file-icons/vagrant.svg?no-inline';
import valaGlyph from '../assets/file-icons/vala.svg?no-inline';
import vimGlyph from '../assets/file-icons/vim.svg?no-inline';
import webassemblyGlyph from '../assets/file-icons/webassembly.svg?no-inline';
import webgpuGlyph from '../assets/file-icons/webgpu.svg?no-inline';
import xcodeGlyph from '../assets/file-icons/xcode.svg?no-inline';
import xmlGlyph from '../assets/file-icons/xml.svg?no-inline';
import yamlGlyph from '../assets/file-icons/yaml.svg?no-inline';
import yarnGlyph from '../assets/file-icons/yarn.svg?no-inline';
import zigGlyph from '../assets/file-icons/zig.svg?no-inline';
import zshGlyph from '../assets/file-icons/zsh.svg?no-inline';
import clojureOriginalBrand from '../assets/file-icons/clojure-original.svg?no-inline';
import cmakeOriginalBrand from '../assets/file-icons/cmake-original.svg?no-inline';
import dartOriginalBrand from '../assets/file-icons/dart-original.svg?no-inline';
import elmOriginalBrand from '../assets/file-icons/elm-original.svg?no-inline';
import intellijOriginalBrand from '../assets/file-icons/intellij-original.svg?no-inline';
import javascriptOriginalBrand from '../assets/file-icons/javascript-original.svg?no-inline';
import juliaOriginalBrand from '../assets/file-icons/julia-original.svg?no-inline';
import jupyterOriginalBrand from '../assets/file-icons/jupyter-original.svg?no-inline';
import kotlinOriginalBrand from '../assets/file-icons/kotlin-original.svg?no-inline';
import nixosOriginalBrand from '../assets/file-icons/nixos-original.svg?no-inline';
import pythonOriginalBrand from '../assets/file-icons/python-original.svg?no-inline';
import rOriginalBrand from '../assets/file-icons/r-original.svg?no-inline';
import racketOriginalBrand from '../assets/file-icons/racket-original.svg?no-inline';
import vuejsOriginalBrand from '../assets/file-icons/vuejs-original.svg?no-inline';

export const FALLBACK_FILE_ICON: FileIconData = { kind: 'phosphor', name: 'file', tint: null };

export const PHOSPHOR_ICONS = {
  'brackets-curly': BracketsCurlyIcon,
  'coffee': CoffeeIcon,
  'file': FileIcon,
  'file-sql': FileSqlIcon,
  'gif': GifIcon,
  'image': ImageIcon,
  'terminal': TerminalIcon,
};

/**
 * A file icon, one of:
 * - `glyph`: a monochrome mark, painted in its tint.
 * - `brand`: a brand icon in its original colors.
 * - `phosphor`: a Phosphor icon whose color defaults to the theme's ink.
 * - `letters`: one to three letters whose color defaults to the theme's ink.
 */
export type FileIconData =
  | { kind: 'glyph'; src: string; tint: IconTint }
  | { kind: 'brand'; src: string }
  | { kind: 'phosphor'; name: keyof typeof PHOSPHOR_ICONS; tint: IconTint | null }
  | { kind: 'letters'; letters: string; tint: IconTint | null };

/**
 * An icon's CSS colors in light and dark variants.
 */
export interface IconTint {
  light: string;
  dark: string;
}

export const FILENAME_ICONS: Record<string, FileIconData> = {
  '.Rprofile': { kind: 'brand', src: rOriginalBrand },
  '.bash_aliases': { kind: 'phosphor', name: 'terminal', tint: null },
  '.bash_profile': { kind: 'phosphor', name: 'terminal', tint: null },
  '.bashrc': { kind: 'phosphor', name: 'terminal', tint: null },
  '.clang-format': { kind: 'glyph', src: llvmGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  '.clang-tidy': { kind: 'glyph', src: llvmGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  '.clangd': { kind: 'glyph', src: llvmGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  '.coveragerc': { kind: 'brand', src: pythonOriginalBrand },
  '.devcontainer.json': { kind: 'glyph', src: developmentcontainersGlyph, tint: { light: '#2753E3', dark: '#3566f6' } },
  '.dockerignore': { kind: 'glyph', src: dockerGlyph, tint: { light: '#2496ED', dark: '#2496ED' } },
  '.editorconfig': { kind: 'glyph', src: editorconfigGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  '.emacs': { kind: 'glyph', src: gnuemacsGlyph, tint: { light: '#7F5AB6', dark: '#8460bc' } },
  '.env': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.env.development': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.env.example': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.env.local': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.env.production': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.env.test': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  '.envrc': { kind: 'phosphor', name: 'terminal', tint: null },
  '.eslintignore': { kind: 'glyph', src: eslintGlyph, tint: { light: '#4B32C3', dark: '#6a5ced' } },
  '.eslintrc.json': { kind: 'glyph', src: eslintGlyph, tint: { light: '#4B32C3', dark: '#6a5ced' } },
  '.flake8': { kind: 'brand', src: pythonOriginalBrand },
  '.git-blame-ignore-revs': { kind: 'glyph', src: gitGlyph, tint: { light: '#F03C2E', dark: '#F03C2E' } },
  '.gitattributes': { kind: 'glyph', src: gitGlyph, tint: { light: '#F03C2E', dark: '#F03C2E' } },
  '.gitconfig': { kind: 'glyph', src: gitGlyph, tint: { light: '#F03C2E', dark: '#F03C2E' } },
  '.gitignore': { kind: 'glyph', src: gitGlyph, tint: { light: '#F03C2E', dark: '#F03C2E' } },
  '.gitmodules': { kind: 'glyph', src: gitGlyph, tint: { light: '#F03C2E', dark: '#F03C2E' } },
  '.htaccess': { kind: 'glyph', src: apacheGlyph, tint: { light: '#D22128', dark: '#da2b2f' } },
  '.npmignore': { kind: 'glyph', src: npmGlyph, tint: { light: '#CB3837', dark: '#cf3c3a' } },
  '.npmrc': { kind: 'glyph', src: npmGlyph, tint: { light: '#CB3837', dark: '#cf3c3a' } },
  '.profile': { kind: 'phosphor', name: 'terminal', tint: null },
  '.pylintrc': { kind: 'brand', src: pythonOriginalBrand },
  '.stylelintignore': { kind: 'glyph', src: stylelintGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  '.tmux.conf': { kind: 'glyph', src: tmuxGlyph, tint: { light: '#00a90d', dark: '#1BB91F' } },
  '.vimrc': { kind: 'glyph', src: vimGlyph, tint: { light: '#019733', dark: '#019733' } },
  '.zprofile': { kind: 'glyph', src: zshGlyph, tint: { light: '#F15A24', dark: '#F15A24' } },
  '.zshenv': { kind: 'glyph', src: zshGlyph, tint: { light: '#F15A24', dark: '#F15A24' } },
  '.zshrc': { kind: 'glyph', src: zshGlyph, tint: { light: '#F15A24', dark: '#F15A24' } },
  'App.config': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'BUILD': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'BUILD.bazel': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'Brewfile': { kind: 'glyph', src: homebrewGlyph, tint: { light: '#c78300', dark: '#FBB040' } },
  'CITATION.cff': { kind: 'glyph', src: yamlGlyph, tint: { light: '#CB171E', dark: '#da2c2c' } },
  'CMakeLists.txt': { kind: 'brand', src: cmakeOriginalBrand },
  'CODEOWNERS': { kind: 'glyph', src: githubGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'Caddyfile': { kind: 'glyph', src: caddyGlyph, tint: { light: '#1F88C0', dark: '#1F88C0' } },
  'Cargo.lock': { kind: 'glyph', src: rustGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'Containerfile': { kind: 'glyph', src: podmanGlyph, tint: { light: '#892CA0', dark: '#a64bbe' } },
  'Dockerfile': { kind: 'glyph', src: dockerGlyph, tint: { light: '#2496ED', dark: '#2496ED' } },
  'Fastfile': { kind: 'glyph', src: fastlaneGlyph, tint: { light: '#00a900', dark: '#00F200' } },
  'GNUmakefile': { kind: 'letters', letters: 'MK', tint: { light: '#427819', dark: '#498023' } },
  'Gemfile': { kind: 'glyph', src: rubygemsGlyph, tint: { light: '#E9573F', dark: '#E9573F' } },
  'Gemfile.lock': { kind: 'glyph', src: rubygemsGlyph, tint: { light: '#E9573F', dark: '#E9573F' } },
  'Jenkinsfile': { kind: 'glyph', src: jenkinsGlyph, tint: { light: '#D24939', dark: '#D24939' } },
  'Justfile': { kind: 'glyph', src: justGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'MODULE.bazel': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'Makefile': { kind: 'letters', letters: 'MK', tint: { light: '#427819', dark: '#498023' } },
  'Package.resolved': { kind: 'glyph', src: swiftGlyph, tint: { light: '#F05138', dark: '#F05138' } },
  'Pipfile': { kind: 'brand', src: pythonOriginalBrand },
  'Pipfile.lock': { kind: 'brand', src: pythonOriginalBrand },
  'Podfile': { kind: 'glyph', src: cocoapodsGlyph, tint: { light: '#EE3322', dark: '#EE3322' } },
  'Rakefile': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'Vagrantfile': { kind: 'glyph', src: vagrantGlyph, tint: { light: '#1868F2', dark: '#1a69f3' } },
  'WORKSPACE': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'WORKSPACE.bazel': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'Web.config': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'bun.lock': { kind: 'glyph', src: bunGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'composer.lock': { kind: 'glyph', src: composerGlyph, tint: { light: '#885630', dark: '#9a6740' } },
  'deno.lock': { kind: 'glyph', src: denoGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'devcontainer.json': { kind: 'glyph', src: developmentcontainersGlyph, tint: { light: '#2753E3', dark: '#3566f6' } },
  'flake.lock': { kind: 'brand', src: nixosOriginalBrand },
  'go.mod': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'go.sum': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'go.work': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'gradlew': { kind: 'glyph', src: gradleGlyph, tint: { light: '#02303A', dark: '#4f7984' } },
  'gradlew.bat': { kind: 'glyph', src: gradleGlyph, tint: { light: '#02303A', dark: '#4f7984' } },
  'jsconfig.json': { kind: 'brand', src: javascriptOriginalBrand },
  'justfile': { kind: 'glyph', src: justGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'makefile': { kind: 'letters', letters: 'MK', tint: { light: '#427819', dark: '#498023' } },
  'mix.lock': { kind: 'glyph', src: elixirGlyph, tint: { light: '#4B275F', dark: '#8963a1' } },
  'mvnw': { kind: 'glyph', src: apachemavenGlyph, tint: { light: '#C71A36', dark: '#d72f42' } },
  'mvnw.cmd': { kind: 'glyph', src: apachemavenGlyph, tint: { light: '#C71A36', dark: '#d72f42' } },
  'nginx.conf': { kind: 'glyph', src: nginxGlyph, tint: { light: '#009639', dark: '#009639' } },
  'pdm.lock': { kind: 'glyph', src: pdmGlyph, tint: { light: '#AC75D7', dark: '#AC75D7' } },
  'poetry.lock': { kind: 'glyph', src: poetryGlyph, tint: { light: '#4f93e7', dark: '#60A5FA' } },
  'pom.xml': { kind: 'glyph', src: apachemavenGlyph, tint: { light: '#C71A36', dark: '#d72f42' } },
  'project.godot': { kind: 'glyph', src: godotengineGlyph, tint: { light: '#478CBF', dark: '#478CBF' } },
  'requirements.txt': { kind: 'glyph', src: pypiGlyph, tint: { light: '#3775A9', dark: '#3977ab' } },
  'tsconfig.json': { kind: 'glyph', src: typescriptGlyph, tint: { light: '#3178C6', dark: '#3178C6' } },
  'uv.lock': { kind: 'glyph', src: uvGlyph, tint: { light: '#db5ce6', dark: '#DE5FE9' } },
  'yarn.lock': { kind: 'glyph', src: yarnGlyph, tint: { light: '#2C8EBB', dark: '#2C8EBB' } },
};

export const EXTENSION_ICONS: Record<string, FileIconData> = {
  'abap': { kind: 'glyph', src: sapGlyph, tint: { light: '#0099e7', dark: '#0FAAFF' } },
  'ada': { kind: 'glyph', src: adaGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'adb': { kind: 'glyph', src: adaGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'adoc': { kind: 'glyph', src: asciidoctorGlyph, tint: { light: '#E40046', dark: '#E40046' } },
  'ads': { kind: 'glyph', src: adaGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'ahk': { kind: 'glyph', src: autohotkeyGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'aidl': { kind: 'glyph', src: androidGlyph, tint: { light: '#00a75c', dark: '#3DDC84' } },
  'anim': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'apex': { kind: 'letters', letters: 'Apx', tint: { light: '#1797c0', dark: '#1797c0' } },
  'apng': { kind: 'phosphor', name: 'image', tint: null },
  'app.src': { kind: 'glyph', src: erlangGlyph, tint: { light: '#A90533', dark: '#cf3a50' } },
  'asciidoc': { kind: 'glyph', src: asciidoctorGlyph, tint: { light: '#E40046', dark: '#E40046' } },
  'asd': { kind: 'glyph', src: commonlispGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'asm': { kind: 'letters', letters: 'ASM', tint: { light: '#6E4C13', dark: '#8f6c36' } },
  'asset': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'astro': { kind: 'glyph', src: astroGlyph, tint: { light: '#BC52EE', dark: '#BC52EE' } },
  'avif': { kind: 'phosphor', name: 'image', tint: null },
  'awk': { kind: 'letters', letters: 'AWK', tint: { light: '#c30e9b', dark: '#cd22a4' } },
  'axaml': { kind: 'glyph', src: avaloniauiGlyph, tint: { light: '#165BFF', dark: '#2265ff' } },
  'bash': { kind: 'phosphor', name: 'terminal', tint: null },
  'bat': { kind: 'letters', letters: 'BAT', tint: { light: '#7c9d00', dark: '#C1F12E' } },
  'bats': { kind: 'phosphor', name: 'terminal', tint: null },
  'bb': { kind: 'letters', letters: 'BB', tint: { light: '#009ec1', dark: '#00bce4' } },
  'bbappend': { kind: 'letters', letters: 'BB', tint: { light: '#009ec1', dark: '#00bce4' } },
  'bbclass': { kind: 'letters', letters: 'BB', tint: { light: '#009ec1', dark: '#00bce4' } },
  'bib': { kind: 'glyph', src: latexGlyph, tint: { light: '#008080', dark: '#008080' } },
  'blade': { kind: 'glyph', src: laravelGlyph, tint: { light: '#FF2D20', dark: '#FF2D20' } },
  'blade.php': { kind: 'glyph', src: laravelGlyph, tint: { light: '#FF2D20', dark: '#FF2D20' } },
  'bmp': { kind: 'phosphor', name: 'image', tint: null },
  'bzl': { kind: 'glyph', src: bazelGlyph, tint: { light: '#43A047', dark: '#43A047' } },
  'c': { kind: 'glyph', src: cGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'cabal': { kind: 'glyph', src: haskellGlyph, tint: { light: '#5D4F85', dark: '#776aa2' } },
  'cc': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'cfg': { kind: 'letters', letters: 'CFG', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'cginc': { kind: 'letters', letters: 'HLS', tint: { light: '#7c9d2b', dark: '#aace60' } },
  'cjs': { kind: 'brand', src: javascriptOriginalBrand },
  'cl': { kind: 'glyph', src: commonlispGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'clj': { kind: 'brand', src: clojureOriginalBrand },
  'cljc': { kind: 'brand', src: clojureOriginalBrand },
  'cljs': { kind: 'brand', src: clojureOriginalBrand },
  'cls': { kind: 'glyph', src: latexGlyph, tint: { light: '#008080', dark: '#008080' } },
  'cmake': { kind: 'brand', src: cmakeOriginalBrand },
  'cmd': { kind: 'letters', letters: 'CMD', tint: { light: '#7c9d00', dark: '#C1F12E' } },
  'code-workspace': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'coffee': { kind: 'glyph', src: coffeescriptGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'cpp': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'cppm': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'cr': { kind: 'glyph', src: crystalGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'cs': { kind: 'letters', letters: 'C#', tint: { light: '#7355dd', dark: '#785ae3' } },
  'cshtml': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'csproj': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'css': { kind: 'glyph', src: cssGlyph, tint: { light: '#663399', dark: '#8c5ac3' } },
  'csv': { kind: 'letters', letters: 'CSV', tint: { light: '#237346', dark: '#338153' } },
  'csx': { kind: 'letters', letters: 'C#', tint: { light: '#7355dd', dark: '#785ae3' } },
  'cts': { kind: 'glyph', src: typescriptGlyph, tint: { light: '#3178C6', dark: '#3178C6' } },
  'cu': { kind: 'glyph', src: nvidiaGlyph, tint: { light: '#66a100', dark: '#76B900' } },
  'cue': { kind: 'letters', letters: 'CUE', tint: { light: '#5886E1', dark: '#5886E1' } },
  'cuh': { kind: 'glyph', src: nvidiaGlyph, tint: { light: '#66a100', dark: '#76B900' } },
  'cxx': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'dart': { kind: 'brand', src: dartOriginalBrand },
  'desktop': { kind: 'glyph', src: freedesktopdotorgGlyph, tint: { light: '#3B80AE', dark: '#3B80AE' } },
  'dockerfile': { kind: 'glyph', src: dockerGlyph, tint: { light: '#2496ED', dark: '#2496ED' } },
  'dot': { kind: 'letters', letters: 'DOT', tint: { light: '#2596be', dark: '#2596be' } },
  'editorconfig': { kind: 'glyph', src: editorconfigGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'edn': { kind: 'brand', src: clojureOriginalBrand },
  'ejs': { kind: 'glyph', src: ejsGlyph, tint: { light: '#869a33', dark: '#B4CA65' } },
  'el': { kind: 'glyph', src: gnuemacsGlyph, tint: { light: '#7F5AB6', dark: '#8460bc' } },
  'elm': { kind: 'brand', src: elmOriginalBrand },
  'env': { kind: 'glyph', src: dotenvGlyph, tint: { light: '#a59200', dark: '#ECD53F' } },
  'erb': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'erl': { kind: 'glyph', src: erlangGlyph, tint: { light: '#A90533', dark: '#cf3a50' } },
  'ex': { kind: 'glyph', src: elixirGlyph, tint: { light: '#4B275F', dark: '#8963a1' } },
  'exs': { kind: 'glyph', src: elixirGlyph, tint: { light: '#4B275F', dark: '#8963a1' } },
  'f': { kind: 'glyph', src: fortranGlyph, tint: { light: '#734F96', dark: '#8762ab' } },
  'f77': { kind: 'glyph', src: fortranGlyph, tint: { light: '#734F96', dark: '#8762ab' } },
  'f90': { kind: 'glyph', src: fortranGlyph, tint: { light: '#734F96', dark: '#8762ab' } },
  'f95': { kind: 'glyph', src: fortranGlyph, tint: { light: '#734F96', dark: '#8762ab' } },
  'feature': { kind: 'glyph', src: cucumberGlyph, tint: { light: '#00a84f', dark: '#23D96C' } },
  'fish': { kind: 'glyph', src: fishshellGlyph, tint: { light: '#00a90e', dark: '#34C534' } },
  'frag': { kind: 'glyph', src: openglGlyph, tint: { light: '#5586A4', dark: '#5586A4' } },
  'fs': { kind: 'glyph', src: fsharpGlyph, tint: { light: '#378BBA', dark: '#378BBA' } },
  'fsi': { kind: 'glyph', src: fsharpGlyph, tint: { light: '#378BBA', dark: '#378BBA' } },
  'fsproj': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'fsx': { kind: 'glyph', src: fsharpGlyph, tint: { light: '#378BBA', dark: '#378BBA' } },
  'g4': { kind: 'letters', letters: 'G4', tint: { light: '#6e93cc', dark: '#9DC3FF' } },
  'gd': { kind: 'glyph', src: godotengineGlyph, tint: { light: '#478CBF', dark: '#478CBF' } },
  'gdshader': { kind: 'glyph', src: godotengineGlyph, tint: { light: '#478CBF', dark: '#478CBF' } },
  'gemspec': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'geojson': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'geom': { kind: 'glyph', src: openglGlyph, tint: { light: '#5586A4', dark: '#5586A4' } },
  'gif': { kind: 'phosphor', name: 'gif', tint: null },
  'gleam': { kind: 'glyph', src: gleamGlyph, tint: { light: '#c378b9', dark: '#FFAFF3' } },
  'glsl': { kind: 'glyph', src: openglGlyph, tint: { light: '#5586A4', dark: '#5586A4' } },
  'go': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'gohtml': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'gotmpl': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'gql': { kind: 'glyph', src: graphqlGlyph, tint: { light: '#E10098', dark: '#E10098' } },
  'gradle': { kind: 'glyph', src: gradleGlyph, tint: { light: '#02303A', dark: '#4f7984' } },
  'gradle.kts': { kind: 'glyph', src: gradleGlyph, tint: { light: '#02303A', dark: '#4f7984' } },
  'graphql': { kind: 'glyph', src: graphqlGlyph, tint: { light: '#E10098', dark: '#E10098' } },
  'graphqls': { kind: 'glyph', src: graphqlGlyph, tint: { light: '#E10098', dark: '#E10098' } },
  'groovy': { kind: 'glyph', src: apachegroovyGlyph, tint: { light: '#4298B8', dark: '#4298B8' } },
  'gv': { kind: 'letters', letters: 'DOT', tint: { light: '#2596be', dark: '#2596be' } },
  'h': { kind: 'glyph', src: cGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'haml': { kind: 'letters', letters: 'HAM', tint: { light: '#9c925c', dark: '#ece2a9' } },
  'handlebars': { kind: 'glyph', src: handlebarsdotjsGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'hbs': { kind: 'glyph', src: handlebarsdotjsGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'hcl': { kind: 'glyph', src: terraformGlyph, tint: { light: '#844FBA', dark: '#8d59c4' } },
  'heex': { kind: 'glyph', src: phoenixframeworkGlyph, tint: { light: '#FD4F00', dark: '#FD4F00' } },
  'heic': { kind: 'phosphor', name: 'image', tint: null },
  'heif': { kind: 'phosphor', name: 'image', tint: null },
  'hh': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'hlsl': { kind: 'letters', letters: 'HLS', tint: { light: '#7c9d2b', dark: '#aace60' } },
  'hlsli': { kind: 'letters', letters: 'HLS', tint: { light: '#7c9d2b', dark: '#aace60' } },
  'hpp': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'hrl': { kind: 'glyph', src: erlangGlyph, tint: { light: '#A90533', dark: '#cf3a50' } },
  'hs': { kind: 'glyph', src: haskellGlyph, tint: { light: '#5D4F85', dark: '#776aa2' } },
  'htm': { kind: 'glyph', src: html5Glyph, tint: { light: '#E34F26', dark: '#E34F26' } },
  'html': { kind: 'glyph', src: html5Glyph, tint: { light: '#E34F26', dark: '#E34F26' } },
  'http': { kind: 'letters', letters: 'HTP', tint: { light: '#005C9C', dark: '#2976b8' } },
  'hx': { kind: 'glyph', src: haxeGlyph, tint: { light: '#dd7605', dark: '#EA8220' } },
  'hxx': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'icns': { kind: 'phosphor', name: 'image', tint: null },
  'ico': { kind: 'phosphor', name: 'image', tint: null },
  'iml': { kind: 'brand', src: intellijOriginalBrand },
  'inc': { kind: 'glyph', src: phpGlyph, tint: { light: '#777BB4', dark: '#777BB4' } },
  'ini': { kind: 'letters', letters: 'INI', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'inl': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'ino': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'ipp': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'ipynb': { kind: 'brand', src: jupyterOriginalBrand },
  'ixx': { kind: 'glyph', src: cplusplusGlyph, tint: { light: '#00599C', dark: '#2b75bb' } },
  'j2': { kind: 'glyph', src: jinjaGlyph, tint: { light: '#7E0C1B', dark: '#bd4e4e' } },
  'java': { kind: 'phosphor', name: 'coffee', tint: { light: '#d37d00', dark: '#f89820' } },
  'jfif': { kind: 'phosphor', name: 'image', tint: null },
  'jinja': { kind: 'glyph', src: jinjaGlyph, tint: { light: '#7E0C1B', dark: '#bd4e4e' } },
  'jinja2': { kind: 'glyph', src: jinjaGlyph, tint: { light: '#7E0C1B', dark: '#bd4e4e' } },
  'jl': { kind: 'brand', src: juliaOriginalBrand },
  'jpeg': { kind: 'phosphor', name: 'image', tint: null },
  'jpg': { kind: 'phosphor', name: 'image', tint: null },
  'js': { kind: 'brand', src: javascriptOriginalBrand },
  'json': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'json5': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'jsonc': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'jsonl': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'jsp': { kind: 'phosphor', name: 'coffee', tint: { light: '#d37d00', dark: '#f89820' } },
  'jsx': { kind: 'glyph', src: reactGlyph, tint: { light: '#039fbe', dark: '#61DAFB' } },
  'just': { kind: 'glyph', src: justGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'kt': { kind: 'brand', src: kotlinOriginalBrand },
  'kts': { kind: 'brand', src: kotlinOriginalBrand },
  'ld': { kind: 'letters', letters: 'LD', tint: null },
  'lean': { kind: 'letters', letters: 'LEA', tint: null },
  'less': { kind: 'glyph', src: lessGlyph, tint: { light: '#1D365D', dark: '#57739f' } },
  'liquid': { kind: 'glyph', src: shopifyGlyph, tint: { light: '#67a048', dark: '#7AB55C' } },
  'lisp': { kind: 'glyph', src: commonlispGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'll': { kind: 'glyph', src: llvmGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'lua': { kind: 'glyph', src: luaGlyph, tint: { light: '#000080', dark: '#396be1' } },
  'luau': { kind: 'glyph', src: luauGlyph, tint: { light: '#0097ef', dark: '#00A2FF' } },
  'm': { kind: 'letters', letters: 'OC', tint: { light: '#438eff', dark: '#438eff' } },
  'mak': { kind: 'letters', letters: 'MK', tint: { light: '#427819', dark: '#498023' } },
  'markdown': { kind: 'glyph', src: markdownGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'mat': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'md': { kind: 'glyph', src: markdownGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'mdx': { kind: 'glyph', src: mdxGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'mermaid': { kind: 'glyph', src: mermaidGlyph, tint: { light: '#FF3670', dark: '#FF3670' } },
  'meta': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'mjs': { kind: 'brand', src: javascriptOriginalBrand },
  'mk': { kind: 'letters', letters: 'MK', tint: { light: '#427819', dark: '#498023' } },
  'ml': { kind: 'glyph', src: ocamlGlyph, tint: { light: '#EC6813', dark: '#EC6813' } },
  'mli': { kind: 'glyph', src: ocamlGlyph, tint: { light: '#EC6813', dark: '#EC6813' } },
  'mm': { kind: 'letters', letters: 'OC', tint: { light: '#6866fb', dark: '#6866fb' } },
  'mmd': { kind: 'glyph', src: mermaidGlyph, tint: { light: '#FF3670', dark: '#FF3670' } },
  'mts': { kind: 'glyph', src: typescriptGlyph, tint: { light: '#3178C6', dark: '#3178C6' } },
  'nasm': { kind: 'letters', letters: 'ASM', tint: { light: '#6E4C13', dark: '#8f6c36' } },
  'nim': { kind: 'glyph', src: nimGlyph, tint: { light: '#a49200', dark: '#FFE953' } },
  'nimble': { kind: 'glyph', src: nimGlyph, tint: { light: '#a49200', dark: '#FFE953' } },
  'nims': { kind: 'glyph', src: nimGlyph, tint: { light: '#a49200', dark: '#FFE953' } },
  'nix': { kind: 'brand', src: nixosOriginalBrand },
  'nu': { kind: 'glyph', src: nushellGlyph, tint: { light: '#4E9A06', dark: '#4E9A06' } },
  'odin': { kind: 'glyph', src: odinGlyph, tint: { light: '#3882D2', dark: '#3882D2' } },
  'org': { kind: 'glyph', src: orgGlyph, tint: { light: '#699b8b', dark: '#77AA99' } },
  'pas': { kind: 'letters', letters: 'PAS', tint: { light: '#8e9900', dark: '#E3F171' } },
  'pbtxt': { kind: 'letters', letters: 'PB', tint: null },
  'php': { kind: 'glyph', src: phpGlyph, tint: { light: '#777BB4', dark: '#777BB4' } },
  'phtml': { kind: 'glyph', src: phpGlyph, tint: { light: '#777BB4', dark: '#777BB4' } },
  'pkl': { kind: 'brand', src: pythonOriginalBrand },
  'pl': { kind: 'glyph', src: perlGlyph, tint: { light: '#0073A1', dark: '#117aa8' } },
  'plantuml': { kind: 'letters', letters: 'UML', tint: { light: '#b98a00', dark: '#fbbd16' } },
  'plist': { kind: 'glyph', src: appleGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'pm': { kind: 'glyph', src: perlGlyph, tint: { light: '#0073A1', dark: '#117aa8' } },
  'png': { kind: 'phosphor', name: 'image', tint: null },
  'po': { kind: 'letters', letters: 'PO', tint: null },
  'podspec': { kind: 'glyph', src: cocoapodsGlyph, tint: { light: '#EE3322', dark: '#EE3322' } },
  'prefab': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'prisma': { kind: 'glyph', src: prismaGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'props': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'proto': { kind: 'letters', letters: 'PB', tint: null },
  'ps1': { kind: 'letters', letters: 'PS', tint: { light: '#012456', dark: '#4d73ac' } },
  'psd1': { kind: 'letters', letters: 'PS', tint: { light: '#012456', dark: '#4d73ac' } },
  'psm1': { kind: 'letters', letters: 'PS', tint: { light: '#012456', dark: '#4d73ac' } },
  'pug': { kind: 'glyph', src: pugGlyph, tint: { light: '#A86454', dark: '#A86454' } },
  'puml': { kind: 'letters', letters: 'UML', tint: { light: '#b98a00', dark: '#fbbd16' } },
  'purs': { kind: 'glyph', src: purescriptGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'py': { kind: 'brand', src: pythonOriginalBrand },
  'pyi': { kind: 'brand', src: pythonOriginalBrand },
  'pyw': { kind: 'brand', src: pythonOriginalBrand },
  'pyx': { kind: 'brand', src: pythonOriginalBrand },
  'qmd': { kind: 'glyph', src: quartoGlyph, tint: { light: '#39729E', dark: '#3e77a3' } },
  'qml': { kind: 'glyph', src: qtGlyph, tint: { light: '#00a92e', dark: '#41CD52' } },
  'r': { kind: 'brand', src: rOriginalBrand },
  'rake': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'razor': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'rb': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'rbi': { kind: 'glyph', src: rubyGlyph, tint: { light: '#CC342D', dark: '#d13a32' } },
  'rego': { kind: 'letters', letters: 'OPA', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'resx': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'rkt': { kind: 'brand', src: racketOriginalBrand },
  'rmd': { kind: 'brand', src: rOriginalBrand },
  'robot': { kind: 'glyph', src: robotframeworkGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'rs': { kind: 'glyph', src: rustGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'rst': { kind: 'letters', letters: 'RST', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  's': { kind: 'letters', letters: 'ASM', tint: { light: '#6E4C13', dark: '#8f6c36' } },
  'sass': { kind: 'glyph', src: sassGlyph, tint: { light: '#CC6699', dark: '#CC6699' } },
  'sbt': { kind: 'glyph', src: scalaGlyph, tint: { light: '#DC322F', dark: '#DC322F' } },
  'scad': { kind: 'glyph', src: openscadGlyph, tint: { light: '#aa9000', dark: '#F9D72C' } },
  'scala': { kind: 'glyph', src: scalaGlyph, tint: { light: '#DC322F', dark: '#DC322F' } },
  'scm': { kind: 'letters', letters: 'SCM', tint: { light: '#1e4aec', dark: '#3163ff' } },
  'scss': { kind: 'glyph', src: sassGlyph, tint: { light: '#CC6699', dark: '#CC6699' } },
  'sh': { kind: 'phosphor', name: 'terminal', tint: null },
  'shader': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'sln': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'slnx': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'snap': { kind: 'glyph', src: jestGlyph, tint: { light: '#C21325', dark: '#d73036' } },
  'sol': { kind: 'glyph', src: solidityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'sql': { kind: 'phosphor', name: 'file-sql', tint: null },
  'storyboard': { kind: 'glyph', src: xcodeGlyph, tint: { light: '#147EFB', dark: '#147EFB' } },
  'sty': { kind: 'glyph', src: latexGlyph, tint: { light: '#008080', dark: '#008080' } },
  'styl': { kind: 'glyph', src: stylusGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'sv': { kind: 'letters', letters: 'SV', tint: { light: '#8e9478', dark: '#DAE1C2' } },
  'svelte': { kind: 'glyph', src: svelteGlyph, tint: { light: '#FF3E00', dark: '#FF3E00' } },
  'svg': { kind: 'phosphor', name: 'image', tint: null },
  'svh': { kind: 'letters', letters: 'SV', tint: { light: '#8e9478', dark: '#DAE1C2' } },
  'swift': { kind: 'glyph', src: swiftGlyph, tint: { light: '#F05138', dark: '#F05138' } },
  'targets': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'tcl': { kind: 'letters', letters: 'TCL', tint: { light: '#a68f5d', dark: '#e4cc98' } },
  'tex': { kind: 'glyph', src: latexGlyph, tint: { light: '#008080', dark: '#008080' } },
  'textproto': { kind: 'letters', letters: 'PB', tint: null },
  'tf': { kind: 'glyph', src: terraformGlyph, tint: { light: '#844FBA', dark: '#8d59c4' } },
  'tfstate': { kind: 'glyph', src: terraformGlyph, tint: { light: '#844FBA', dark: '#8d59c4' } },
  'tftpl': { kind: 'glyph', src: terraformGlyph, tint: { light: '#844FBA', dark: '#8d59c4' } },
  'tfvars': { kind: 'glyph', src: terraformGlyph, tint: { light: '#844FBA', dark: '#8d59c4' } },
  'tif': { kind: 'phosphor', name: 'image', tint: null },
  'tiff': { kind: 'phosphor', name: 'image', tint: null },
  'tmpl': { kind: 'glyph', src: goGlyph, tint: { light: '#009ec6', dark: '#00ADD8' } },
  'tofu': { kind: 'glyph', src: opentofuGlyph, tint: { light: '#aa9000', dark: '#FFDA18' } },
  'toml': { kind: 'glyph', src: tomlGlyph, tint: { light: '#9C4121', dark: '#b45737' } },
  'tres': { kind: 'glyph', src: godotengineGlyph, tint: { light: '#478CBF', dark: '#478CBF' } },
  'trigger': { kind: 'letters', letters: 'Apx', tint: { light: '#1797c0', dark: '#1797c0' } },
  'ts': { kind: 'glyph', src: typescriptGlyph, tint: { light: '#3178C6', dark: '#3178C6' } },
  'tscn': { kind: 'glyph', src: godotengineGlyph, tint: { light: '#478CBF', dark: '#478CBF' } },
  'tsv': { kind: 'letters', letters: 'TSV', tint: { light: '#237346', dark: '#338153' } },
  'tsx': { kind: 'glyph', src: reactGlyph, tint: { light: '#039fbe', dark: '#61DAFB' } },
  'twig': { kind: 'glyph', src: symfonyGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'txt': { kind: 'letters', letters: 'TXT', tint: null },
  'typ': { kind: 'glyph', src: typstGlyph, tint: { light: '#239DAD', dark: '#239DAD' } },
  'unity': { kind: 'glyph', src: unityGlyph, tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'vala': { kind: 'glyph', src: valaGlyph, tint: { light: '#7239B3', dark: '#8c56d1' } },
  'vb': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'vbproj': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'vcxproj': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'vert': { kind: 'glyph', src: openglGlyph, tint: { light: '#5586A4', dark: '#5586A4' } },
  'vhd': { kind: 'letters', letters: 'VHD', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'vhdl': { kind: 'letters', letters: 'VHD', tint: { light: '#1c2430', dark: '#e9e4d8' } },
  'vim': { kind: 'glyph', src: vimGlyph, tint: { light: '#019733', dark: '#019733' } },
  'vue': { kind: 'brand', src: vuejsOriginalBrand },
  'wat': { kind: 'glyph', src: webassemblyGlyph, tint: { light: '#654FF0', dark: '#6b58f9' } },
  'webmanifest': { kind: 'phosphor', name: 'brackets-curly', tint: { light: '#8B5CF6', dark: '#8B5CF6' } },
  'webp': { kind: 'phosphor', name: 'image', tint: null },
  'wgsl': { kind: 'glyph', src: webgpuGlyph, tint: { light: '#005A9C', dark: '#2a76ba' } },
  'xaml': { kind: 'glyph', src: dotnetGlyph, tint: { light: '#512BD4', dark: '#6d56fc' } },
  'xhtml': { kind: 'glyph', src: html5Glyph, tint: { light: '#E34F26', dark: '#E34F26' } },
  'xib': { kind: 'glyph', src: xcodeGlyph, tint: { light: '#147EFB', dark: '#147EFB' } },
  'xml': { kind: 'glyph', src: xmlGlyph, tint: { light: '#005FAD', dark: '#2374c3' } },
  'xsd': { kind: 'glyph', src: xmlGlyph, tint: { light: '#005FAD', dark: '#2374c3' } },
  'xsl': { kind: 'glyph', src: xmlGlyph, tint: { light: '#005FAD', dark: '#2374c3' } },
  'xslt': { kind: 'glyph', src: xmlGlyph, tint: { light: '#005FAD', dark: '#2374c3' } },
  'y': { kind: 'letters', letters: 'Y', tint: { light: '#4B6C4B', dark: '#597b59' } },
  'yaml': { kind: 'glyph', src: yamlGlyph, tint: { light: '#CB171E', dark: '#da2c2c' } },
  'yml': { kind: 'glyph', src: yamlGlyph, tint: { light: '#CB171E', dark: '#da2c2c' } },
  'zig': { kind: 'glyph', src: zigGlyph, tint: { light: '#c98200', dark: '#F7A41D' } },
  'zig.zon': { kind: 'glyph', src: zigGlyph, tint: { light: '#c98200', dark: '#F7A41D' } },
  'zsh': { kind: 'phosphor', name: 'terminal', tint: null },
};
